"""
Render the project's docs as Jupyter notebooks so the markdown displays nicely.

Each .md/.txt doc becomes a .ipynb under docs_notebooks/, split into markdown
cells by H2 (## ) section so each block renders on its own. Content is copied
verbatim (this is a view, not an edit), so just re-run any time the docs change.

Run: thesis-venv/bin/python scripts/make_doc_notebooks.py
"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # repo root
os.chdir(ROOT)
OUT = "docs_notebooks"
os.makedirs(OUT, exist_ok=True)

# (source path, output notebook name)
# FIX hardcoded list, any new doc has to be added here by hand
FILES = [
    ("manuals/README.md",            "01_README.ipynb"),
    ("manuals/GUIDE.md",             "02_GUIDE.ipynb"),
    ("manuals/SCRIPTS.md",           "03_SCRIPTS.ipynb"),
    ("manuals/DATA.md",              "04_DATA.ipynb"),
    ("manuals/RESULTS.md",           "05_RESULTS.ipynb"),
    ("manuals/THESIS_LOG.md",        "06_THESIS_LOG.ipynb"),     # verbatim
    ("WHAT_WE_FOUND.md",             "07_WHAT_WE_FOUND.ipynb"),
    ("hyperparam/README.md",         "08_HYPERPARAMETERS.ipynb"),
    ("data/feature_experiments/README.md",                       "09_DATA_feature_experiments.ipynb"),
    ("README.md",                                    "10_MASTER_README.ipynb"),
    ("documentation/02_architecture_spec/ARCHITECTURE.md", "11_ARCHITECTURE.ipynb"),
    ("experiments/2026-06-14_m1m2_autoencoder_validity/README.md",     "12_EXP_autoencoder_validity.ipynb"),
    ("experiments/2026-06-14_input_feature_screen/README.md",          "13_EXP_input_feature_screen.ipynb"),
]

def md_to_cells(text):
    """split markdown into cells at each H2 (## ...) so blocks render separately."""
    cells, cur = [], []
    for ln in text.split("\n"):
        if ln.startswith("## ") and any(c.strip() for c in cur):
            cells.append(cur); cur = [ln]
        else:
            cur.append(ln)
    if cur:
        cells.append(cur)
    out = []
    for block in cells:
        src = "\n".join(block).strip("\n")
        if not src.strip():
            continue
        lines = src.split("\n")
        source = [l + "\n" for l in lines[:-1]] + [lines[-1]]   # nbformat wants a line list, last line no trailing newline
        out.append({"cell_type": "markdown", "metadata": {}, "source": source})
    return out

def make_nb(cells):
    return {"cells": cells, "metadata": {"language_info": {"name": "python"},
            "kernelspec": {"name": "python3", "display_name": "Python 3"}},
            "nbformat": 4, "nbformat_minor": 5}

made = 0
index_lines = ["# Docs — notebook versions\n",
               "Rendered markdown views of the project docs (auto-generated by "
               "`scripts/make_doc_notebooks.py`). Open any to read with formatted markdown.\n"]
for src, name in FILES:
    if not os.path.exists(src):
        print(f"  skip (missing): {src}")
        continue
    with open(src) as f:
        text = f.read()
    nb = make_nb(md_to_cells(text))
    with open(os.path.join(OUT, name), "w") as f:
        json.dump(nb, f, indent=1)
    print(f"  {src}  ->  {OUT}/{name}  ({len(nb['cells'])} cells)")
    index_lines.append(f"- [{name}](./{name}) — from `{src}`\n")
    made += 1

with open(os.path.join(OUT, "00_INDEX.md"), "w") as f:
    f.write("\n".join(index_lines))
print(f"\nwrote {made} notebooks -> {OUT}/  (+ 00_INDEX.md)")
print("DOCNB_DONE")
